### ISSUE TITLE
always error

### ISSUE THREAD

**Issue by nevertoday** [consensual-hallucination/midjourney-dl#2]
python midjourney-dl.py

#----------------------------------#
# Midjourney Archive Downloader    #
# v0.0.1                           #
#----------------------------------#

Midjourney App Build ID: 4EwJhiNhsS7YXQFUwbbMr

Who's archive do you want to download? (Enter for your own):

1. Download images for a specific date
2. Download all images

Enter your choice: 1
Day (1-31, 'Enter' for Today): 31
Month (1-12, 'Enter' for current month): 5
Year ('Enter' for current year):
Traceback (most recent call last):
  File "/Users/admin/Downloads/CODE-mj下载/midjourney-dl.py", line 222, in <module>
    get_archive_by_date(API_URL)
  File "/Users/admin/Downloads/CODE-mj下载/midjourney-dl.py", line 128, in get_archive_by_date
    response = requests.get(API_URL, cookies=COOKIES, headers=HEADERS)
  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1285, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1326, in _send_request
    self.putheader(hdr, value)
  File "/opt/homebrew/lib/python3.9/site-packages/urllib3/connection.py", line 224, in putheader
    _HTTPConnection.putheader(self, header, *values)
  File "/opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1263, in putheader
    raise ValueError('Invalid header value %r' % (values[i],))
ValueError: Invalid header value b *********************************************

**Comment by consensual-hallucination** [comment]
Don't post your token publicly (it's your password). I have removed it from your post. 
I no longer have access to Midjourney and I may not be able to debug this. 
If Midjourney did not change anything, all you need to do is update your token but if they did you will need to debug it yourself.
